# Generated by Django 4.1.1 on 2022-10-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emanil',
            new_name='email',
        ),
    ]
